name: Generate and Download Keystore
on:
  workflow_dispatch:   # This makes it manual trigger only
    inputs:
      org_name:
        description: 'HL Test Organization'
        required: true
        default: 'MyTestOrganization'
      city:
        description: 'TestCity'
        required: true
        default: 'MyTestCity'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v \
          -keystore my-release-key.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias my-key-alias \
          -dname "CN=${{ github.inputs.org_name }}, OU=${{ github.inputs.org_name }}, O=${{ github.inputs.org_name }}, L=${{ github.inputs.city }}, S=State, C=US" \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }}

      # Create key.properties file
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=my-key-alias" >> key.properties
          echo "storeFile=../my-release-key.jks" >> key.properties

      # Encrypt keystore for future GitHub Actions use
      - name: Encrypt Keystore
        run: |
          openssl aes-256-cbc -salt -in my-release-key.jks -out my-release-key.jks.enc -k ${{ secrets.KEYSTORE_PASSWORD }}
          echo "Keystore encrypted successfully"
          base64 my-release-key.jks.enc > encoded_keystore.txt
          echo "SAVE THIS VALUE AS YOUR ENCODED_KEYSTORE SECRET:" > secrets_guide.txt
          cat encoded_keystore.txt >> secrets_guide.txt

      # Upload files as artifacts
      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: keystore-files
          path: |
            my-release-key.jks
            key.properties
            secrets_guide.txt
          retention-days: 1  # Short retention for security
